### ISSUE TITLE
[Question] Using red-band for the representation

### ISSUE THREAD

**Issue by akasom89** [pytroll/pyspectral#219]
Thanks for this awesome package. In the docs, it was mentioned that the Red band is used for representation. I couldn't fully understand the purpose.

`This Rayleigh (including Mie scattering and aborption by aerosols) contribution should then of course be subtracted from the data. Optionally the red band can be provided as the fifth argument, which will provide a more gentle scaling in cases of high reflectances (above 20%):`

`refl_cor_m2 = viirs.get_reflectance(sunz, satz, ssadiff, 'M2', redband)`

what is the purpose behind this redband? if the correction is only dependent on geometry and band wavelength? 

As in almost all atmospheric correction configs for SatPy, the red band is also assigned as the prerequisite. I think that is the same argument. is it? 
```
  rayleigh_corrected:
    modifier: !!python/name:satpy.modifiers.PSPRayleighReflectance
    atmosphere: us-standard
    aerosol_type: rayleigh_only
    prerequisites:
    - name: B03
      modifiers: [sunz_corrected]
```

Thanks in advance

(My main question was whether those configs apply corrections based on the red band or not? So, I dug more into the PySpectral library and just found the representation band argument, which seems to be the same thing.)
